<!DOCTYPE log [
        <!ELEMENT log (array)*>
        <!ELEMENT array (data|part|time|meth)*>
        <!ELEMENT data (heading|men|contracts|budget|action|parameters|cost|extras|status)*>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT men (#PCDATA)>
        <!ELEMENT contracts (amount|resource)*>
        <!ELEMENT amount (#PCDATA)>
        <!ELEMENT resource (#PCDATA)>
        <!ELEMENT budget (#PCDATA)>
        <!ELEMENT part (#PCDATA)>
        <!ELEMENT time (#PCDATA)>
        <!ELEMENT meth (#PCDATA)>
        <!ELEMENT action (#PCDATA)>
        <!ELEMENT parameters (message|direction|creek|people|resource|ex)*>
        <!ELEMENT message (#PCDATA)>
        <!ELEMENT direction (#PCDATA)>
        <!ELEMENT cost (#PCDATA)>
        <!ELEMENT extras (found|range|biomes|creeks|resources|pois|amount)*>
        <!ELEMENT found (#PCDATA)>
        <!ELEMENT range (#PCDATA)>
        <!ELEMENT status (#PCDATA)>
        <!ELEMENT biomes (#PCDATA)>
        <!ELEMENT creeks (#PCDATA)>
        <!ELEMENT creek (#PCDATA)>
        <!ELEMENT people (#PCDATA)>
        <!ELEMENT resources (amount|resource|cond)*>
        <!ELEMENT cond (#PCDATA)>
        <!ELEMENT pois (kind|id)*>
        <!ELEMENT kind (#PCDATA)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT ex (#PCDATA)>
        ]>
<log>
<array>
<data>
<heading>
N</heading>
<men>
15</men>
<contracts>
<amount>
50</amount>
<resource>
RUM</resource>
</contracts>
<contracts>
<amount>
300</amount>
<resource>
LEATHER</resource>
</contracts>
<contracts>
<amount>
500</amount>
<resource>
QUARTZ</resource>
</contracts>
<contracts>
<amount>
10000</amount>
<resource>
WOOD</resource>
</contracts>
<budget>
20000</budget>
</data>
<part>
Engine</part>
<time>
1458550337338</time>
<meth>
initialize</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<message>
Calibrating Coords</message>
<direction>
W</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337345</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
<found>
OUT_OF_RANGE</found>
<range>
52</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337346</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<message>
Determine Width</message>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337346</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
3</cost>
<extras>
<found>
OUT_OF_RANGE</found>
<range>
0</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337346</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<message>
Determine starting pos</message>
<direction>
N</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337347</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
<found>
OUT_OF_RANGE</found>
<range>
52</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337347</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
heading</action>
<parameters>
<direction>
W</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337353</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337353</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
3</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
3</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
3</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
3</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337354</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
2</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337355</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
3</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
2</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
2</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
3</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337356</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337357</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
2</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
3</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
2</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337358</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
3</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337359</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337360</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337360</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337360</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
3</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337360</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337360</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
2</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337360</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
heading</action>
<parameters>
<direction>
N</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337360</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337360</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337360</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
7</cost>
<extras>
<found>
OUT_OF_RANGE</found>
<range>
52</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337361</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337361</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
2</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337361</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337361</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
<found>
OUT_OF_RANGE</found>
<range>
52</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337361</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337362</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337362</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337362</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
7</cost>
<extras>
<found>
GROUND</found>
<range>
21</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337362</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337362</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337362</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337362</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
7</cost>
<extras>
<found>
GROUND</found>
<range>
20</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337363</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337363</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
3</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337363</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337363</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
<found>
GROUND</found>
<range>
20</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337363</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337364</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
2</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337364</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337364</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
<found>
GROUND</found>
<range>
6</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337364</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337364</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337364</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337364</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
<found>
GROUND</found>
<range>
6</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337364</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337364</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
2</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337364</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337364</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
8</cost>
<extras>
<found>
GROUND</found>
<range>
5</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
2</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
<found>
GROUND</found>
<range>
5</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
7</cost>
<extras>
<found>
GROUND</found>
<range>
5</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
4</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
<found>
GROUND</found>
<range>
5</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337365</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
<found>
GROUND</found>
<range>
6</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
<found>
GROUND</found>
<range>
6</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
2</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>
<parameters>
<direction>
E</direction>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
6</cost>
<extras>
<found>
GROUND</found>
<range>
5</range>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
fly</action>
<parameters>
</parameters>
</data>
<part>
Explorer</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<cost>
5</cost>
<extras>
</extras>
<status>
OK</status>
</data>
<part>
Engine</part>
<time>
1458550337366</time>
<meth>
takeDecision</meth>
</array>
<array>
<data>
<action>
echo</action>